---
title: "giyyui"
output: github_document
date: '2022-07-10'
---

```{r setup, message=FALSE,warning=FALSE}
library(dbplyr)
library(tidyverse)
library(tidyr)
library(stringi)
```


```{r,}
library(readxl)
data_cleaned_2021 <- read_excel("data_cleaned_2021.xlsx")
View(data_cleaned_2021)
library("tidyr")
```


```{r pressure, echo=FALSE}
#newmin=substr(data_cleaned_2021$`Salary Estimate`,2,4)
#data_cleaned_2021$newmin=gsub("K","",(newmin))%>%as.numeric()


```
```{r}
nw=separate(data= data_cleaned_2021[,"Salary Estimate"],col= `Salary Estimate`,into= c("emp","min","max","glassdoor") ,sep ="([$()])")
```


```{r}
nw$sourse=ifelse(is.na(nw$glassdoor),nw$emp,nw$glassdoor)
```


```{r}
nw$hourly=grepl(pattern = "H",nw$max,ignore.case = TRUE)
nw$min=as.numeric(gsub("[^[:digit:]]","",nw$min))
nw$max=as.numeric(gsub("[^[:digit:]]","",nw$max))
#data_cleaned_2021$newmaxx=gsub("K","",(nw$o))%>%as.numeric()

```

```{r}
#ty= cbind(data_cleaned_2021$newmin,data_cleaned_2021$newmaxx)
data_cleaned_2021$Aver=rowMeans(ty)
```

```{r}
df=data_cleaned_2021%>%select(`Salary Estimate`)%>%sample_n(100)
```

```{r}
dff=data_cleaned_2021%>%select(`Salary Estimate`)%>%sample_n(100)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
```{r}
clean=cbind.data.frame(data_cleaned_2021,nw)
```



